<a href="https://colab.research.google.com/github/pradeep-kkumar/Database-Connectivity/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

#Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

#Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:

In [1]:
import numpy

In [2]:
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np

arr1 = np.array([2,4,6,8,10])
print(arr1)

[ 2  4  6  8 10]


#Checking NumPy Version
The version string is stored under __version__ attribute.

In [6]:
print(np.__version__)

2.0.2


#Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [7]:
arr2 = np.array("1,2,3,4,5,6,7,8")
print(arr2)
print(type(arr2))

1,2,3,4,5,6,7,8
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [8]:
arr2 = np.array(("1,2,3,4,5,6,7,8"))
print(arr2)
print(type(arr2))

1,2,3,4,5,6,7,8
<class 'numpy.ndarray'>


#Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

*nested array: are arrays that have arrays as their elements.*

###0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:
a1 = np.array(10)

print(a1)

10


##1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [10]:
a2 = np.array([1,2,3,4,5])
a2

array([1, 2, 3, 4, 5])

##2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [12]:
a3 = np.array([[1,2,3,4],[5,6,7,8]])
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [15]:
a4 = np.array([[[1,2,3], [4,5,6]], [[3,2,1], [6,5,4]]])
a4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]]])

##Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [20]:
print("Dimension of the a1 : ", a1.ndim)
print("Dimension of the a2 : ", a2.ndim)
print("Dimension of the a3 : ", a3.ndim)
print("Dimension of the a4 : ", a4.ndim)

Dimension of the a1 :  0
Dimension of the a2 :  1
Dimension of the a3 :  2
Dimension of the a4 :  3


##Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [25]:
a5 = np.array([1,2,3,4,5], ndmin=6)
print("Dimension of the a5 : ", a5.ndim)

Dimension of the a5 :  6
